### ISSUE TITLE
Suggestion: Seeder/fertilizer direct to refill route

### ISSUE THREAD

**Issue by Karlshoj** [Courseplay/courseplay#1014]
Due to the shape of the fields and the layout of the roads it is not always the point where you enter the field that will be the starting point for your fieldwork. When the implement is empty you have to go to either the first or the last point of the field route before heading the refill route. I would like that I could head the refill route route directly from the point where the implement got empty. Same is relevant when collecting grass or straw with the pickup trailer. Possible?
Niels

**Comment by OldFisher** [comment]
That would be definite improvement. Unload/refill courses will need to be remade, but it will save some time and fuel and maybe prevent some collisions.

**Comment by AndyK70** [comment]
As i understand this: @Karlshoj wants to have the direct route from stop-working-point (seeder empty, loader wagon full, etc.) to the unload course. @OldFisher wants to have the vehicle to continue driving the field course after reaching the stop-working-point to leave the field...
Aren't those wishes diametrical opposed?

I used to have one course to get to the working "field" as first, then the begin of working field marked with a waitingpoint, then driving the work course, marking the end of working course with a second waitingpoint and driving off the "field" to the next crossing point to the unload course where recording stops.
The second course is a course to the BGA (if greenfield is not right the neighborhood like at field 15), third is unloading at the BGA and fourth would be from BGA back to field.

@Developer:
When the trailer has unloaded and finished the combined course it drives to the first waypoint of all and not to the first waypoint where the field (first waitingpoint set) begins.
Is this intended? 
When recording my first courses I was assuming CP would drive to the waypoint where the field course begins (waitingpoint) before resuming the work and not to the very first waypoint of the course. 

Or another example where I'm not very happy with that behavior: When the driver has finished to pick the grass on a mowed greenfield I stop the driver, clear the course and give him a new combination:
1. from here, drive to next greenfield
2. working course
3. unloading course
4. back to greenfield course

When the driver has done his first unloading and returned to the field he wants to drive to the first waypoint of the fist course, which only was to get him from the last field to this one...
Would operate way better, if CP would drive directly to the begin of the field course where he waitingpoint is set and from there on continue to it's saved waypoint to collect/work/seed more.

**Comment by OldFisher** [comment]
"Aren't those wishes diametrical opposed?"
Not at all. We both think that instead of going to the end point of work course, the vehicle should go right to the unload/refill course. The only difference is *how* it goes - blindly and directly, or staying inside the working lane. Or maybe driving back the lane if necessary.

"It would be too risky to go straight to the (first waypoint of the) unload course."
But going straight to the endpoint is just as risky: it all depends on field shape and obstacles around. In fact, making the vehicle exit the field via the current lane could make it safer.

"Driving the whole course to leave the field is very safe"
It's too impractical even to be considered.

**Comment by AndyK70** [comment]
oh, ok. I misunderstood your thoughts. I thought you meant to drive the whole field course ...
You want the vehicle drive on until it reaches the "turnstart" trigger and from there to the the unload course.
How do you (CP in fact) know where the unload course begins?
If the courses are merged together, there is no marker like a waitingpoint or turnstart/turnend to signal CP "hey, here starts the unload course."
So how to tell CP?

**Comment by Karlshoj** [comment]
The unload course starts at the firts point after the "end of fieldwork waiting point". As far as I understand two waiting point are automatically added when you generate the field course -one at the start and one at the end. If you record the field course you must add those points manually.
Imagine a field course starting at the NE corner heading W and ending at the SW corner, then your refill/unload course should start somewhere on that line, and end at the NE corner of the field. Say that the refill/ unload course starts close to the NW corner - having free sight to any point of the field -, and the seeder, fertilizer, bale loader or forage wagon runs full/empty in the middle of the field, it doesn`t make sence that the tractor firts goes to NE corner(return to start active) or to the SW corner(return not active) before heading to the NW corner to catch the refill/unload course.
Little hard for me to explain in writing - hope I succeded.

**Comment by OldFisher** [comment]
Wait, guys, I'm gonna do some pictures to clarify things.

**Comment by Karlshoj** [comment]
Sorry for my drawing skills. Anyway this is my wish

![refill](https://cloud.githubusercontent.com/assets/7414065/5992127/16cb9ef2-aa01-11e4-8f42-46a57a43ef56.jpg)

**Comment by AndyK70** [comment]
very nice... and now dream of work courses with unload/refill course which are not rectangular:
![greenfield at BGA](http://www11.pic-upload.de/02.02.15/c68ubelcm59y.jpg)

The beginning of the work course is not the beginning of the work as the first waitingpoint is set later.
but that's another thing. I will edit the work course that it will have the starting point as waitingpoint right next to the end of the unloading course, but that's not the problem here. 
It's just the shape.
Now reconsider your thoughts with that "field" :grinning:

**Comment by Karlshoj** [comment]
I guess that I would split such a field in two

**Comment by OldFisher** [comment]
Since it's not a field and this course does not have lanes, my dreams are just not applicable to it. So no problem there: no lanes - no lanewise entry/exit.

**Comment by AndyK70** [comment]
@OldFisher so how could CP distinguish combined/merged courses which have a recorded course from a generated course?

And this was only an extrem example to show you an irregular shape, it's not about lanes.
I have combined field 24 and 25 and generated courses for it. It has a nice L shape.
What about those?
![http://www11.pic-upload.de/02.02.15/rmlkurutiyu.jpg](combined field24+25)

If the loading wagon is in the north-east section and would drive the second-last or fourth-last line while getting full, it would drive to the end, then heading for unload course and fall down the cliff...

**Comment by OldFisher** [comment]
@AndyK70

CP stores the "generated" attribute for each generated waypoint. Some other interesting stuff too.

Also for this L-shaped field my idea would work perfectly, if the refill course is remade accordingly (that is, make it start near north-east corner of the field, and return the same way, but a little bit more to the east. The tractor would drive across the lane to the eastern side of the field, start on refill course (not from its starting point, but from the point closest to the lane exit), refill and proceed until it can enter the lane again (from point of the rest of the course that is closest to the lane entry). Check my picture, it shows that new refill route now covers all the lanes, and the return part is a bit further from the field.

**Comment by AndyK70** [comment]
I know it stores this attributes in the XML, but does it consider those when driving and when it which way?

For this L-shape it may work, does it work even, when the north-east section would extend more to north?
For going backwards the lane to exit. I don't think it would be applicable for the script to decide when to go forward and when to go backwards, but let's hear what Jakob and the others think of.
Same applies for exit/entry at closest point to the unload/refill course.
If it is not even applicable to reenter work at the marker (waitingpoint, see #1023) how would it be possible to develop your dream?

**Comment by Karlshoj** [comment]
When starting this thread I made a suggestion. OldFisher presented another idea. Now I believe it`s for the developers to evaluae if they like the ideas or not.

**Comment by ThomasGaertner** [comment]
we've discussed this issue and made a decision. we want to follow @Karlshoj and let the empty seeder / full forage wagon go directly to the first point of the unloading/refilling course. returning will be the same at the moment. please test v 0073 or higher and report....

**Comment by Karlshoj** [comment]
I have tested with the forage wagon. Looks ok apart from the speed between the full load point and the first point of the unload route which drops to 4 kmh. I would prefer field speed at that leg. Waiting for the fields to be harvested before I can test the seeder/fertilizer. Thanks for what we have got until now

**Comment by ThomasGaertner** [comment]
@Karlshoj : fixed in 0076...

**Comment by AndyK70** [comment]
Tested with 0075 and looks good to me.
From point where filllevel was 100% to first point from unload course was driving with 20km/h.
When it came back it was driving from last point unload course to current point field course with 24km/h (field speed in settings).

dunno why @Karlshoj had it at 4km/h

**Comment by ThomasGaertner** [comment]
depending of the recorded speed of the first waypoint....

**Comment by AndyK70** [comment]
Suspected it already and checked my unloading course in CourseDrawer.
First waypoint of unloading course had 0 km/h, 2nd waypoint had 26km/h.
The field work course was generated, so all waypoints where set to 0km/h
So I didn't find any congruence...
hmmm
but if this is already fixed in 0076 I don't bother.

**Comment by Karlshoj** [comment]
Also Works perfect for me when using the forage wagon. Did´t finish the harvest yet so still missing the seeder/fertilizer test.

**Comment by ThomasGaertner** [comment]
@AndyK70 : I assume that your 3rd waypoint has something around 50kmh so its the average of 4 points.... btw

**Comment by Karlshoj** [comment]
It all works perfect. Thanks a lot

**Comment by AndyK70** [comment]
Maybe I'm seeing this issue again in mode 6 with mowing grass (Kuhn FC3525F) and attached Euroboss 330T.
First course is working course with two waiting-points marking start and end. Second attached course is unload course to a selling tip trigger for grass.

When trailer is full, tractor drives to end point of first course, then continuing to the unload course, tipping the grass, driving the unload course to it's end and then driving to first waypoint of working course.
I read again and the return was not altered, but when trailer is full it shouldn't drive to last waypoint of working course, should it?

I'm now on standard WBH with CP v0089
[FS15 logfile (2015-02-25 23:50)](https://gist.github.com/AndyK70/50784a0554b1a14087a6#file-fs15-logfile-2015-02-25-23-50)

**Comment by ThomasGaertner** [comment]
I will test it, could you test again with debug channel 12 active and posts the log and maybe you courses...

**Comment by AndyK70** [comment]
The Log: [FS15 logfile (2015-02-26 17:40)](https://gist.github.com/AndyK70/2651c58c970f5dcb8eda#file-fs15-logfile-2015-02-26-17-40)
The two courses I used: [Wiese F13 West - Westbridge Hill](https://gist.github.com/AndyK70/a4d92366f17738092ddc#file-wiese-f13-west-westbridge-hill)

When the tractor was on it' first run on that course I recognized it wouldn't fill up the trailer until finish, so I stopped the driver, manually mowed some grass until 95% fill level and then continued the course.
When trailer was full, it drove to end of working course, not straight to beginning of unloading course.

**Comment by ThomasGaertner** [comment]
let me tell you something about the way we decide, where to go in this situation:
when you connect the courses together, all the waypoints will be put in a table.
To decide, where the field work starts and ends , we use the waiting points.
That means for your case: the field work starts at waypoint 2 and stop at 321.
If the trailer is full , we set the target waypoint to stop work + 1
And now the riddle of the day: 
looking to your waypoints, where will it go then ? :-)

**Comment by AndyK70** [comment]
ok, understood :grinning: 

Then it's something about recording?
Even when I come to full stop before setting waiting-point end right after that end recording without moving an inch there will be two waypoints on the same spot. One with the waiting-point marker and one with the cross-marker.

I can edit those in coursedrawer, removing the waypoint with the waiting-point an setting the waiting-point to the last waypoint with the crossing-point.
But what should any other user do, to have waiting-point and crossing-point (end of course) set at the same last waypoint of the course?

**Comment by ThomasGaertner** [comment]
K I checked it and I really don't want to change script on this place, tried it without the crossing there.
worked . I don't, think the crossing is really necessary after the wait, because the script will add the closest crossing of the second course to the last point of the first one if there is no crossing...
try out .....

**Comment by AndyK70** [comment]
would like to, but the crossing is inserted automatically when I hit "stop recording"...

**Comment by ThomasGaertner** [comment]
arrg ok, will take a moment...

**Comment by AndyK70** [comment]
just an idea, maybe it is easier to change the insertion of the last point (when hitting stop recording)?
That way:
* If the last recorded waypoint is not more than 0.1m away, don't insert a new one, but add the crossing to it.
