### ISSUE TITLE
Tippers don't tip anymore after fixing ver 5.02.00062

### ISSUE THREAD

**Issue by JLConradie** [Courseplay/courseplay#2636]
Hello Every one!!
Thanks for all the changes over the last 3 months.. great job.

OK.. I've loaded version 5.02.00061 and works fine.. Loaded version 5.02.00062 and the game stuck
with error....
Error: Running LUA method 'update'.
C:/Users/Louis/Documents/My Games/FarmingSimulator2017/mods/courseplay/drive.lua:1250: attempt to index field 'fillTriggers' (a nil value).,

Repeatedly... around 100 or so times in log file. 

It only happens on sell route from farm to sell point just before the farm silo trigger.. or fill trigger.

I thought it might be my trailer but it's doing the same with mods or game trailers..
I've tested it with other maps as well.. the same happens.

Well.. I wouldn't be surprised if it only happens to me.
Although I'over 50... my mother always told me... I'm a one in a million guy. 

Regards...
Louis Conradie...

**Comment by TinyCrocodile** [comment]
I assume it comes from a recent small change in mode 1 to try fixing issue with multiple trigger in mode 1. 
See #2051
And commit  382ae50
the error apears to be exactly in the changed code. I guess it does something with the covers. Do differen cover settings change the error?

**Comment by JLConradie** [comment]
No.. All the same.. Trailers with or without Covers. Same error.. Sorry..

**Comment by TinyCrocodile** [comment]
Try newest version @pops64 fixed it in 0063.

**Comment by JLConradie** [comment]
OOO did not even see... mmm Sorry.. I'll try immediately!!!

THANKS!..

You know I was just thinking.. It works fine on field loading at combine and tip at farm Silo.. Covers reacting as they should. open close..  As soon as you / courseplay wants to fill at farm silo the error appears.. Maybe the trigger does not get registered at start up.. Well.. just a wild guess... I had some C++ programming experience for the last 20 odd years... on and off.. 

OK I'll test and report back..

**Comment by JLConradie** [comment]
IT WORKS!!!!..

Well done...
I tested it with mods.. and game trailers.. Trailers with covers and without..  Works every time..

Thank you so much!..

Regards
Louis Conradie
Western Cape, South Africa

**Comment by ThomasGaertner** [comment]
@nbhubbard96 :  with v.63 and higher ?

**Comment by nbhubbard96** [comment]
i was on v.62 . i updated to v.64 and it fixed that problem. now the trailer wont unload at the grain bins it just drives on over the trigger

**Comment by ThomasGaertner** [comment]
can you give me more details? map, mode, maybe savegame ??

**Comment by JLConradie** [comment]
Thomas.. this issue has been fix by @pops64 in ver 5.02.00063.
Ver 5.02.00063 works very well.

Thank You..

**Comment by nbhubbard96** [comment]
Map is broad acres. Running mode 1 grain transport. Unloading from coolaman mother bin and dumping at farm bin

**Comment by ThomasGaertner** [comment]
@nbhubbard96 : can you give me your courses and savegame ? I can not replicate it ...

**Comment by nbhubbard96** [comment]
Do you need my mods to open the save game or what do you need

**Comment by ThomasGaertner** [comment]
Your savegame folder and the courses folder

**Comment by JLConradie** [comment]
Good Morning @ThomasGaertner 

I tested it with my mod trailer (Ver 66) and everything is working the way it should. Not onece in traffic message. Issue related. Here and there tractors ran into something but understandable. I even turn tractor facing away from combine all in a twisted manner to see if trailer course any in traffic messages.  But none.. 

Trailer tip properly at tip triggers, no problem there.
Trailer load properly on sell route at farm silo and offload at sell trigger/point.
No Problems there too.

All my issues that I had... you fixed with Ver 66.
Once again, Thomas, Thank You.
Thanks that you are always willing to help and to fix user issues.  
And the of course the quick response any time of the day.. Day or night.

THANK YOU

**Comment by nbhubbard96** [comment]
Ok I’ll try the new version and see if it fixed it. If it doesn’t then I will send you my save game. How do I send save game

**Comment by nbhubbard96** [comment]
i was looking over the unsupported mods and noticed the weight station trigger. on broad acres there is a weight station right before the unload trigger. could this be causing my problems

**Comment by pops64** [comment]
Depends how close. But shouldn't. That is for more if the unload is inside the weight station trigger. Has CP only sees the first trigger until is clear of the trigger. So if they are close CP can't clear the wiegh out if memory yes you would have issues. But they would have to be overlapping for this to be a problem

**Comment by nbhubbard96** [comment]
I went into GE and remove the weight station and it still won’t work. What else could it be

**Comment by pops64** [comment]
Please post log with debug channel 1? The channel for load and unload tipper can't remember if it is channel 1

**Comment by nbhubbard96** [comment]
Ok it will be a few days before I can do it

**Comment by nbhubbard96** [comment]
<script src="https://gist.github.com/nbhubbard96/7e59d63eaae7f10c7d657284099e15d5.js"></script>
here is my log file with debug 2 on

**Comment by nbhubbard96** [comment]
https://gist.github.com/nbhubbard96/7e59d63eaae7f10c7d657284099e15d5
here is my log with debug 2 turned on

**Comment by nbhubbard96** [comment]
You said the one for load and unload tippers. That is debug 2

**Comment by nbhubbard96** [comment]
i set up a new course to a different tip trigger and now it is working properly. wonder why it wouldnt work on the other trigger

**Comment by pops64** [comment]
My guess would be the trigger doesn't accept that fill type. That's why asked for channel 2 but it seems there is verbous debug print in with that doesn't belong. So what I was looking for I didn't see

**Comment by nbhubbard96** [comment]
I could unload the trailer my self on the trigger but courseplay wouldn’t. It worked when I first set the course up but then quit working

**Comment by pops64** [comment]
I am combineing all duplicate threads about tip triggers not working into #2661
