### ISSUE TITLE
Helper ignores Sellpoint

### ISSUE THREAD

**Issue by GatorAli** [Courseplay/courseplay#3177]
I got the Problem that my helper is going over the Point but did Not Stop for unloading.

No Mod vehicle.
Want to sell oats at the Port/ harbor via combine Mode.

Tried different methods for the Course... Recoding with full Trailer and unloading at Sellpoint while recoding.
Recoding with full Trailer but dont sell ist.
And recording with empty Trailer.
Tried as Well with different vehicle.
Also installed a new Version of Courseplay 

Got a similar one while selling sugarcane at Sellpoint near field 8 on Ravenport.
But There where 2 helpers in combine Mode selling around 25 Times. Then, Same issue, only following the Course without selling and coming Back to combine with full Trailer.

I make a Backup of this Savegame If this could be helpfull.

**Comment by ThomasGaertner** [comment]
yes savegame and courses please

**Comment by Danatru** [comment]
I'm going to leave a comment here even though I'm playing on a modded version of a mod map (Flusstal), because I'm getting similar issues and I can't help but think that it's related to this issue, and also #3125 and #3046. I could provide a link to the map as well as my savegame and courses if you want. I'm going to include a couple screenshots. 

![fsscreen_2019_02_09_15_37_57](https://user-images.githubusercontent.com/25954730/52526126-1a4aef80-2c82-11e9-91f7-829a67ffe350.png)
![fsscreen_2019_02_09_15_38_12](https://user-images.githubusercontent.com/25954730/52526130-26cf4800-2c82-11e9-8e40-494721e315c0.png)
![fsscreen_2019_02_09_15_39_20](https://user-images.githubusercontent.com/25954730/52526132-2c2c9280-2c82-11e9-82d0-440fbe863473.png)
![fsscreen_2019_02_09_15_39_59](https://user-images.githubusercontent.com/25954730/52526134-32227380-2c82-11e9-8ecb-9161bfadd6bd.png)

The first two (farm silo - not a mod - and an example elevated sell point) courseplay has no issues with in combi mode. The ones that are recessed into the ground it refuses to recognizes the tip triggers and drives straight on through.

**Comment by GatorAli** [comment]
https://1drv.ms/u/s!AssSdLLYvGZ1wUIYSiKzTuNWPtHc
Here is the onedrive Link to a zip wich contains the savegame as well as all my courses just in case.

The course i mentioned is course12, names "F6/12/13 - Hafenspeicher"

Hafenspeicher and Getreidespeicher Zentrum are both roofed points as well as the ones from Danatru wich didnt work... Dont know if there is a context. Just noticed that

**Comment by sootysax** [comment]
Also having this problem at the Silage unload trigger at the BGA on Marwell Manor Farms.

https://gist.github.com/sootysax/963be66aec86981501661ff2d6d67f0d

**Comment by limoman39** [comment]
I was having the same problem on straw sell trigger at the Stock Barn on Honeydew Farms.   I found if I slow the vehicle down it catches the trigger every time.  I even tried it with a mod and it worked.
Great job with Courseplay, looking forward to the finished product.  The game is not the same without it.

**Comment by sootysax** [comment]
This has nothing to do with speed..  the 'tip trigger reached' signal isn't even coming up on the CP display.

**Comment by sootysax** [comment]
Here is another example..  a course that was working in previous versions that I have sold many loads in the past.

As you can see from the screenshots, speed setting has no impact here.  Tip Trigger not recognized as far as i can tell.

https://gist.github.com/sootysax/858596ea1655e5bd6f5ecfdb17f3aee8

![fsscreen_2019_02_13_10_38_09](https://user-images.githubusercontent.com/6591048/52723657-ef131980-2f7b-11e9-9a8a-8d162a418058.png)
![fsscreen_2019_02_13_10_38_15](https://user-images.githubusercontent.com/6591048/52723666-f33f3700-2f7b-11e9-8b12-8779f6c6e0e1.png)

**Comment by ThomasGaertner** [comment]
try it with v93 or higher and report

**Comment by ThomasGaertner** [comment]
@GatorAli : please test with the v.112 or higher. I reworked the tipping system.

**Comment by GatorAli** [comment]
> @GatorAli : please test with the v.112 or higher. I reworked the tipping system.

Done. Wokrs perfect with both sellpoints. This is awesome scripting magic going on :D

**Comment by ThomasGaertner** [comment]
@sootysax  ? what about you ?

**Comment by sootysax** [comment]
@ThomasGaertner working for me on the Wesby Wisconsin grain sell point..  I will recheck the silage bin at the BGA on Marwell and report

**Comment by sootysax** [comment]
https://gist.github.com/sootysax/e534d4c9a49a4c38745c489953aaff9a

Still not dumping into the BGA tip point - though the Start Overloading comes up in the f1 menu.  It backs all the way up and then pulls out without dumping.

![fsscreen_2019_03_03_16_39_58](https://user-images.githubusercontent.com/6591048/53702350-f9367400-3dd3-11e9-9351-ac5e285ff340.png)

I am having a similar issue with the sell milk trigger...  it backs in, starts unloading milk, but does not wait for it to finish, and pulls out after only unloading about 30% of the load.

**Comment by ThomasGaertner** [comment]
@sootysax : V 140 ?
