### ISSUE TITLE
Suggestion: Non-trigger refill waypoints

### ISSUE THREAD

**Issue by GeorgeEarslight** [Courseplay/courseplay#3326]
This is a suggestion about implementing a "wait to be refilled" function on refill courses, instead of requiring a refill trigger.

* The refill course should be recorded with a single Wait Point on the location the AI worker would wait.
* At the waypoint, the player would bring the pallet/IBC/bucketload/tanker etc and commence the refill.
  * The AI worker should open the seed or fertilizer compartment, if applicable.
* In the future the AI worker could cooperate with a Transfer or Bucket AI to automate the whole process.
* The "Refill until percentage" should be observed before the worker leaves to continue work.
* For tools with multiple containers (e.g. seed-fertilizer), the worker should wait for both to be refilled, or it could be an option.

Something to consider if and when Mode4 will be refactored.

**Comment by Knowen** [comment]
I like that idea. If this is possible, it would be nice that CP announce that the worker is waiting at the "wayting for refill"-Waypoint. E.g. like the prompt if the worker reached the end of a course.

**Comment by ThomasGaertner** [comment]
i'm currently working on it for #3243

**Comment by Innallas** [comment]
@ThomasGaertner  i was saying it :D and in fact maybe it's just a condition to add to do the whole thing for waiting to refill , i suggested it to sootysax in #3243 , 30 min ago :D

**Comment by ThomasGaertner** [comment]
@Innallas : I would prefer, if you would let us talk to the issues owners to solve their problems in our way of solving it. If you have a sure working solution and it has been tested on all conditions you are welcome to raise a pull request and we will decide, whether it fits in our concept or not. please don't post modified pieces of our own script here, its not helpfull. 
Thanks

**Comment by ThomasGaertner** [comment]
test v105 or higher and report

**Comment by GeorgeEarslight** [comment]
> test v105 or higher and report

Drove past Wait Point (sprayer) in v105, will test again in latest ver and report.

**Comment by ThomasGaertner** [comment]
@GeorgeEarslight : which sprayer ? if you can replicate it pleas give me the savegame and courses

**Comment by GeorgeEarslight** [comment]
> @GeorgeEarslight : which sprayer ? if you can replicate it pleas give me the savegame and courses

@ThomasGaertner v110 stopped with Condor Seeder, so it could be something with the earlier version.
I'll try to test with the same sprayer (the towed Hardi 6k litre) too on v110.
An issue now is that the seeder compartment is not automatically opened (see [here](https://youtu.be/eBS2eDB8t8M)). Do you need a savegame/course for this?

**Comment by ThomasGaertner** [comment]
nope this is still not implemented...

**Comment by GeorgeEarslight** [comment]
> nope this is still not implemented...

OK, I will report once I test the sprayer. 
Thanks for the feature!

**Comment by GeorgeEarslight** [comment]
> @GeorgeEarslight : which sprayer ? if you can replicate it pleas give me the savegame and courses

@ThomasGaertner https://we.tl/t-dHeHFrcPpE
Just hop on the Fendt 313 and hit drive.
Normally I have a wheel loader near the waiting point, but it's a mod.

**Comment by ThomasGaertner** [comment]
@GeorgeEarslight :test with v.125 or higher

**Comment by GeorgeEarslight** [comment]
@ThomasGaertner Helper stops at the wait point and outputs message **correctly**. Thanks!

The sprayer doesn't "consume" any IBCs I bring close though. Is this implemented? 
Tell me if you need a new save with a telehandler at the wait point, so you can test.

**Comment by ThomasGaertner** [comment]
Yes please

**Comment by GeorgeEarslight** [comment]
@ThomasGaertner https://we.tl/t-QcYkzMeCW6

Got a telehandler near the wait point and some IBCs. 
Tried leaving the IBC on the ground near the helper or driving next to it with the trailer, in case of IBC ownership problems, but still didn't consume them.
The sprayer's position is the same, so you should be able to use the same course and then hop on the telehandler.

**Comment by ThomasGaertner** [comment]
@GeorgeEarslight : why don't you simply drive by the trailer with the pallets without wait point. but please try with v.141 or higher. I've fixed a small bug in there.

**Comment by GeorgeEarslight** [comment]
@ThomasGaertner OK I will try this soon and report.

**Comment by GeorgeEarslight** [comment]
@ThomasGaertner Tested and it checks out. Minor issue was that it doesn't observe the filling quota and just fills till there's nothing else near, but that can be solved if the player stacks the pallets. 

Still won't be able to load with a bucket, but let's close this and move to more critical issues?
