### ISSUE TITLE
MP Server: CP client crashes immediately on clicking Mode 7 Collect icon

### ISSUE THREAD

**Issue by jspring0811** [Courseplay/courseplay#6884]
Tested using Courseplay v6.03.00044
The same savegame works in Career mode but on MP Dedi Server the CP client display (and all game displays in the lower right of the screen) disappears immediately after clicking on the bale collect icon.

Client and server logs attached.  (You can ignore the Static actor moved (goulot1) warnings -- I have had them for months and have not tracked down which mod is responsible).

[client_log.zip](https://github.com/Courseplay/courseplay/files/6023426/client_log.zip)
[server_log.zip](https://github.com/Courseplay/courseplay/files/6023428/server_log.zip)

I believe the issue occurs at:

2021-02-22 10:58 LUA call stack:
2021-02-22 10:58   =C:/Users/Jason/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/settings.lua (49) : printCallstack
2021-02-22 10:58   =C:/Users/Jason/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/vehicles.lua (792) : __index
2021-02-22 10:58   =C:/Users/Jason/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/vehicles.lua (1582) : getToolTurnRadius
2021-02-22 10:58   =C:/Users/Jason/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/BaleCollectorAIDriver.lua (47) : getTurningRadius
2021-02-22 10:58   =C:/Users/Jason/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CpObject.lua (43) : init
2021-02-22 10:58   =[C] (4294967295)
2021-02-22 10:58   =C:/Users/Jason/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/settings.lua (49) : xpcall
2021-02-22 10:58   =C:/Users/Jason/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/settings.lua (22) : setAIDriver
2021-02-22 10:58   setfenv(1,FS19_Courseplay); courseplay:setCpMode(...) (1) : setCpMode
2021-02-22 10:58   =C:/Users/Jason/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/input.lua (183)
2021-02-22 10:58   =C:/Users/Jason/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/input.lua (156) : executeFunction
2021-02-22 10:58   =C:/Users/Jason/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/button.lua (260) : setCourseplayFunc
2021-02-22 10:58   =C:/Users/Jason/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/button.lua (244) : handleInput
2021-02-22 10:58   =C:/Users/Jason/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/input.lua (71) : handleMouseClick
2021-02-22 10:58   =C:/Users/Jason/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CpManager.lua (355) : onMouseEvent
2021-02-22 10:58   dataS/scripts/BaseMission.lua (1418) : mouseEvent
2021-02-22 10:58   dataS/scripts/FSBaseMission.lua (1929) : mouseEvent
2021-02-22 10:58   dataS/scripts/main.lua (1821) : mouseEvent
2021-02-22 10:58 :48 [info lp12075] 410 (#0): Exception, can't init nil, nil
2021-02-22 10:58 Error: Running LUA method 'packetReceived'.
2021-02-22 10:58 C:/Users/Jason/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/base.lua:1070: attempt to call method 'readUpdateStream' (a nil value)
2021-02-22 10:58 Error: Running LUA method 'packetReceived'.

![20210222_CP44_BaleCollect_01](https://user-images.githubusercontent.com/48362683/108737935-130d7c00-7501-11eb-9095-6478a418d050.jpg)
![20210222_CP44_BaleCollect_02](https://user-images.githubusercontent.com/48362683/108737988-1d2f7a80-7501-11eb-8825-dd14f8bdd4cc.jpg)

Thanks

**Comment by Tensuko** [comment]
Is it this what you discribed in #6871 ?

**Comment by jspring0811** [comment]
Yes, exactly.  Moved here to a new issue since that OPs issue was about MP clients not being able to connect.  -Thanks

**Comment by schwiti6190** [comment]
@jspring0811 could you test this branch out: ` https://github.com/Courseplay/courseplay/tree/Issue-%236884`
The error callstack of your logs should be fixed, but I am not sure if there a few other problems :)

**Comment by jspring0811** [comment]
@schwiti6190 Confirmed.  This dev branch is working correctly on my server.  Bales are being collected. Please let me know if you need anything else. -- Thanks!

**Comment by schwiti6190** [comment]
@jspring0811 That's great, did you have any connection problems as mentioned in #6871 on your server with this version ? :)

**Comment by jspring0811** [comment]
@schwiti6190 There were 2 users connected last night after installing CP-dev-6884 and a restart of the Dedi Server.  So, the initial issues of not being able to connect at all and not being able to connect more than one user, at first appeared to be fixed.

However, after I disconnected last night, I was not able to reconnect this morning.  Even after a restart of the Dedi Server, I was still not able to connect (stopped at Synchronizing 29%).  I don't know if this is directly CP related since I have not yet attempted to repeat the scenario with CP removed.

I have attached the most recent server and client logs if you are able to see anything about what is preventing connection -- very much appreciated that you are helping!

[client_log.zip](https://github.com/Courseplay/courseplay/files/6036594/client_log.zip)
[server_log.zip](https://github.com/Courseplay/courseplay/files/6036595/server_log.zip)

**Comment by schwiti6190** [comment]
@jspring0811 thx for your fast answer, MP fixes is like searching for a needle in a haystack :) I updated the version, so you can give it another shot :)

**Comment by jspring0811** [comment]
@schwiti6190 Great! I'll run the same tests this evening & tomorrow morning and get the results back to you.

BTW, Did you see something in the log that was suspicious?  Anything that I would be able to see in either the server or client logs?

**Comment by jspring0811** [comment]
@schwiti6190 Ran another test with the latest copy of the 6884 branch.  I was not able to connect.  I even stopped the server, removed CP, restarted, reconnected, saved, and then added back CP and tried to connect.  After restart with CP enabled it would not connect.

I think there is a specific error message this time right at the Synchronizing step (screenshot and full client & server logs attached)

[server_log.zip](https://github.com/Courseplay/courseplay/files/6040319/server_log.zip)
[client_log.zip](https://github.com/Courseplay/courseplay/files/6040320/client_log.zip)

![20210224_CPv44dev_base_lua_driver_error](https://user-images.githubusercontent.com/48362683/109098148-c4bdd000-76ee-11eb-95a1-8605d759a8a0.jpg)

**Comment by schwiti6190** [comment]
@jspring0811 Unfortunately `attempt to index field 'driver' (a nil value)` is a following error and not the main error, which should be during the Synchronizing step as you have mentioned, sadly our on error detection isn't being printed during the sync. I can only guess what the problem could be. I've updated the branch, only thing left is hoping and praying :)

**Comment by rento112** [comment]
> 
> 
> @jspring0811 Unfortunately `attempt to index field 'driver' (a nil value)` is a following error and not the main error, which should be during the Synchronizing step as you have mentioned, sadly our on error detection isn't being printed during the sync. I can only guess what the problem could be. I've updated the branch, only thing left is hoping and praying :)

I  got good news and bad news about your most recent fix before this reply.

Here's my situation first, The mode 7 does indeed cause me to freeze. At first I couldnt load into the game due to the syncing, then I started a clean save and it let me load into the server just fine. But upon selecting mode 7 bale collector, it frose my game. Upon that, I couldnt join the game anymore, not being able to sync! 

Good news: Doing another new save with the fix, I can load into the game and actually use the Bale collector mode on  the server.

Bad news: The older save gives the middle finger for  syncing.

It could be some kind of file or something  causing the sync to go bad directly related to the Bale Collector mode, affected by the older version, but with the fix, the bale collector doesnt cause the syncing freeze.

**Comment by Tensuko** [comment]
You could try to fix the old save, by remove CP, load it, save your game, add CP and try to start again.
It should throw out most of the stuff.
If this doesn't help, check the vehicles.xml file for CP entries and remove them (in savegame)

**Comment by jspring0811** [comment]
@Tensuko Yes, thanks -- I am always able to fallback to v41 by first removing CP mod and then restarting-saving-restarting.  As long as I do a save in-between without CP then I am able to add back CP v41.

**Comment by rento112** [comment]
> 
> 
> You could try to fix the old save, by remove CP, load it, save your game, add CP and try to start again.
> It should throw out most of the stuff.
> If this doesn't help, check the vehicles.xml file for CP entries and remove them (in savegame)

I've tried that

**Comment by rento112** [comment]
Alright more Bad news. When a second player joined, the server, the sync problem came back. We were able to join at first, but we were stuck in our vehicles.

**Comment by schwiti6190** [comment]
@jspring0811, @rento112 Could you post a log file of the server and the clients with this "Issue-#6884" branch?

**Comment by rento112** [comment]
> 
> 
> @jspring0811, @rento112 Could you post a log file of the server and the clients with this "Issue-#6884" branch?

I unfortunately dont know how to

**Comment by jspring0811** [comment]
@schwiti6190 Yes, I can test again with a couple of users this evening or perhaps tomorrow morning.  And, then I can try a rejoin sometime later tomorrow to see if I am able to reconnect after existing a multi-user dedi session.

My last testing included commits up to and including 6bf7cd4 (Feb 24) so I will be testing commits from Feb 25 and if anything further is committed this afternoon https://github.com/Courseplay/courseplay/commits/Issue-%236884  -- Thanks

**Comment by jspring0811** [comment]
@schwiti6190 Mixed results.  It seems if I start the server then the first user can connect, but after that the next user can not connect -- and no users can connect again (even the first user) until the server is restarted.  A few logs attached below (the sets in the middle 1_ and 2_ are the ones with failures)...

_Server startup **without** CP mod and 1 user connect  (success):
[0_pre_cp_server_log.zip](https://github.com/Courseplay/courseplay/files/6057533/0_pre_cp_server_log.zip)
[0_pre_cp_client_log.zip](https://github.com/Courseplay/courseplay/files/6057526/0_pre_cp_client_log.zip)_

**user2 connect failure after user1:**
[1_user1_connected_user2_cant_connect_server_log.zip](https://github.com/Courseplay/courseplay/files/6057539/1_user1_connected_user2_cant_connect_server_log.zip)
[1_user2_fail_client_log.zip](https://github.com/Courseplay/courseplay/files/6057543/1_user2_fail_client_log.zip)

**user1 and user2 both connect failure:**
[2_user2_connected_and_reconnected_but_user1_cant_connect_server_log.zip](https://github.com/Courseplay/courseplay/files/6057547/2_user2_connected_and_reconnected_but_user1_cant_connect_server_log.zip)
[2_user1_fail_client_log.zip](https://github.com/Courseplay/courseplay/files/6057550/2_user1_fail_client_log.zip)
[2_user2_fail_again_client_log.zip](https://github.com/Courseplay/courseplay/files/6057551/2_user2_fail_again_client_log.zip)

_After restart, user2 connect success:
[3_after_restart_user2_connect_success_server_log.zip](https://github.com/Courseplay/courseplay/files/6057553/3_after_restart_user2_connect_success_server_log.zip)
[3_user2_success_after_restart_client_log.zip](https://github.com/Courseplay/courseplay/files/6057555/3_user2_success_after_restart_client_log.zip)_

**Comment by schwiti6190** [comment]
@jspring0811 Thanks for all the trouble :). This mod seems to have a lot of errors: `fs19_silobolsafuncional` might only be in combination with cp not sure. Could you explain to me what happen in between "Server startup without CP mod and 1 user connect (success)" and "user2 connect failure after user1" on the server, for example have you started a cp driver or did some hud changes. If your up for some more test, than it would be great if you could only use cp, to avoid any possible mod problems.
I suspect this is the problem: "Error: Failed to create new object with class id 6811 in initial object array", but it's really hard to pinpoint which object this is. Unfortunatly I don't really see away to find the problem, then to do a lot of a tests sadly and I don't really have the time for it. To summarize the best test would be to start up the server and join repeatedly and do only minior changes in between to identify the error. If your up for the task, then you can take your time as this will probably be quit time consuming :)

**Comment by jspring0811** [comment]
@schwiti6190 Well, yes a lot going on in each session before the second user tries to join...

I believe the fs19_silobolsafuncional is the Akron bagger.  I can remove that from our mods -- we don't use it anymore (and it wouldn't have been actively used in any of the logs I posted).

I was most curious about these errors from both clients:
2021-02-27 20:26 Error: Running LUA method 'update'.
2021-02-27 20:26 dataS/scripts/vehicles/specializations/FillUnit.lua(625) : attempt to perform arithmetic on field 'capacity' (a nil value)

**Comment by rento112** [comment]
Here's something else that might narrow it down, Similar situuation. But apparently consider the host as a player. Even dedicated servers. When i  was using a dedicated  server with the mod, the branch fix,  it allowed me as a player to join without problems, but once the second player joined, it went to hell. At first, he joined, but we would get in our vehicles, but  we would become stuck in them, unable to  do get out or move them  if I remember correctly. After a retart of our games and even a server restart too, we coudlnt make it past Syncing with other players anymore, even when the server was empty.

Next, I gave up on the dedicated server since it was getting too  laggy to play on anyways, so I went  back to hosting it myself, using the branch fix, it would appear that the second player could connect to me. I do not know about adding a third player in my locally  hosted game would cause the bug again or not since I didnt  have a third player, but I suspect it would happen just like with Jspring. So a sync and use of the programs runs mostly fine when the host(player)  or a dedicated server connects with just 1 additional player with some hitches here and there with the courseplay freezing me inside a tractor one-time. 

Here's the other interesting part, Eventually, the Syncing issue crops back  up anyways even with 1 player, but this can be fixed by removing the and reloading the gsme without it, save and quit, and then reload the mod again. Hypothesis is that when saving with the courseplay mod, it creates an error somewhere in the save that causes an  issue with the sync. Either this problem shows itself during when the host is hosting it again or it directly, unknowing, happens when it's saving potentially.

**Comment by jspring0811** [comment]
@rento112 Except that I am comparing CP mod v41 vs CP mod v44.  If I rollback to v41 then there's no issue connecting.

Recent changes on the v44dev branch have improved this, and I just need time to see if there is a pattern to any remaining issue.

**Comment by rento112** [comment]
> 
> 
> @rento112 Except that I am comparing CP mod v41 vs CP mod v44. If I rollback to v41 then there's no issue connecting.
> 
> Recent changes on the v44dev branch have improved this, and I just need time to see if there is a pattern to any remaining issue.

yeah, I'm just telling what's happened so far with me. Unfortunately I cant do anymore tests since i dont have  anyonee to play with anymore

**Comment by Tensuko** [comment]
Just tried 6.03.00047 Bale Collector on Dedi Server: No Issue.
![Uploading fsScreen_2021_03_02_17_42_59.png…]()

**Comment by jspring0811** [comment]
@Tensuko Ok... but on our server, the fixes in this banch were required to (1) prevent instant crash, and (2) fix reconnection failures:

https://github.com/Courseplay/courseplay/commits/Issue-%236884

I assume they will be merged into a release at some point.

**Comment by rento112** [comment]
> 
> 
> Just tried 6.03.00047 Bale Collector on Dedi Server: No Issue.
> ![fsScreen_2021_03_02_17_42_59](https://user-images.githubusercontent.com/27344744/109682723-f74c4a80-7b7e-11eb-963a-688e18ea19fb.png)

The initial does crop up when a second connection comes into the hostt, which is nice to see that seems to be worked out. But when a third connection comes into play,  the problem happens even with the the branch fix. What I mean by third connection, is that two players and the host. When I used a dedicated server, it had no problem with me connecting to the server, but once the second player(Third connection) joined, it went wack. Works fine when I'm hosting it myself and he connects to me, but the problem does crop up later eventually. Uninstalling and reinstalling the mod fixes it however.

**Comment by Tensuko** [comment]
Can you pls try 6.03.00049 or higher and report ?

**Comment by Tensuko** [comment]
From my own tests, Mode7 is working now on server and even reconnecting with Mode7 working on server does work.

Will close this one, let us know if any more problems with Mode7 in MP.
