### ISSUE TITLE
Tipper Triggers No Longer Recognized.

### ISSUE THREAD

**Issue by PlumbersCrack** [Courseplay/courseplay#904]
I can get logs for this if needed but nothing has changed except I upgraded my courseplay to the newest DEV version.  Was running the original DEV version that was released several weeks ago, the one you had to modify the file to get courseplay to open with the right click, and everything worked fine.  Updated yesterday and now the tip trigger for my BGA Unload never gets recognized.  I take the silage from my silo in a trailer which has a course to load it and tip it at the BGA to sell it.  After upgrading, never recognizes the tip trigger.  I have tried using 3 different tractors and different tippers that are side tip/rear tip/both tip and still nothing.  Debugged on 1 and 2 and doesn't seem to find it.  No notice of tip trigger reached or anything, just blows right by.  As I said before, nothing has changed except newer version of courseplay, thanks.  Oh, using AGS_Map.

**Comment by PlumbersCrack** [comment]
Just loaded back up courseplay v 4.00.0038.dev - loaded the course and finds the tip point without a problem.

**Comment by JakobTischler** [comment]
In which version exactly did it start not working anymore. Also, post your complete log please.

**Comment by schniedertoenz** [comment]
Hi, I have the same problem. The version I am using is 4.01.0026.dev.
The triggers are reachable in manual unloading mode but not using courseplay.
The problem with coursplay starts with the third unloading move.
I use the Ammergauer_Alpen map.

**Comment by JakobTischler** [comment]
> Also, post your complete log please.

Secondly, please provide a link to the map.

**Comment by PlumbersCrack** [comment]
I am using AGS_Map - http://www.modhoster.com/mods/ags-map--3 
Courseplay v.4.01.0018.dev
Log file -  https://gist.github.com/358a9616cf0317397263.git

**Comment by JakobTischler** [comment]
Try again with build 0035 and debug channel 1 active (the channel should be active *before* you start CP in the vehicle in question). As always, post the log.

**Comment by schniedertoenz** [comment]
Here's the link to the map I play:
http://www.modhoster.de/mods/ammergauer-alpen-ls2015

**Comment by schniedertoenz** [comment]
With build 0035 the problem is solved.
Thanks a lot!

**Comment by massey18** [comment]
can someone explain me? what the h*ll is build 0035 and debug channel?

**Comment by ThomasGaertner** [comment]
@massey18 : this is a developer platform where we are improving the script with the help of users.
if you have no idea what 'developer' or 'debug' or 'build' means we ask you to use the already released version and keep the issues area clean for the guys who do

**Comment by massey18** [comment]
now i didn't actually asked what developer means but i now have found out that with debug channel one only the tipper recognizes the trigger. the forage wagons still doesn't empty. but i do want to know what built 0035 means? and yes my post whas a bit rude, sorry for that.

**Comment by AndyK70** [comment]
0035 is the developer version.
turning on a debug channel in courseplay doesn't alter it's functionality or behaviour. It only writes debug information into the log.txt with which the developers can better analyze what has happened.

Better not mess around with options you don't understand.

**Comment by massey18** [comment]
but where can i find version 0035?

**Comment by AndyK70** [comment]
If you don't understand what I was saying, please stay with the official builds to download i.e at modhoster.de, don't mess around here.
